language: c
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
sudo: false
env:
  matrix:
    - GCOV_FLAG=--enable-gcov
    - GCOV_FLAG=
script:
    - ./autogen.sh && ./configure $GCOV_FLAG && make check
    
